### ISSUE TITLE
Need better architecture 

### ISSUE THREAD

**Issue by awtb** [DJPythonSnake/Senya_bot_v2.0#1]
1. You can use eval function for calculating. ([link](https://realpython.com/python-eval-function/))
2. Instead if statements you can use FuzzyWuzzy library ([link](https://github.com/seatgeek/fuzzywuzzy))
3. Also add GUI, because it useful than Terminal interface.

**Comment by DJPythonSnake** [comment]
Thank you for commet. 
Ill fix it soon.
